"""Public release-candidate installer contracts."""

from lea.installers.release_candidate.configuration import (
    BaseConfigurationPlan,
    BaseConfigurationResult,
    ReleaseCandidateInstallationRecord,
    create_base_configuration_plan,
    create_installation_record,
    install_base_configuration,
    render_installation_record,
)
from lea.installers.release_candidate.contracts import (
    InstallerIssue,
    InstallerIssueCode,
    InstallerMutation,
    InstallerMutationKind,
    InstallerStepId,
    InstallerStepPlan,
    InstallerStepResult,
    InstallerStepState,
    ReleaseCandidateInstallMode,
    ReleaseCandidateInstallPlan,
    ReleaseCandidateInstallRequest,
    ReleaseCandidateInstallResult,
)
from lea.installers.release_candidate.preflight import (
    HostFacts,
    HostPreflightCheck,
    HostPreflightCheckState,
    HostPreflightResult,
    collect_host_facts,
    evaluate_host_preflight,
    run_host_preflight,
)
from lea.installers.release_candidate.provisioning import (
    ManagedDirectory,
    SystemProvisioningPlan,
    SystemProvisioningResult,
    create_system_provisioning_plan,
    provision_system_layout,
)
from lea.installers.release_candidate.taskwarrior import (
    ReleaseCandidateTaskwarriorInputs,
    ReleaseCandidateTaskwarriorPlan,
    ReleaseCandidateTaskwarriorResult,
    create_taskwarrior_installation_plan,
    install_release_candidate_taskwarrior,
)

__all__ = [
    "BaseConfigurationPlan",
    "BaseConfigurationResult",
    "HostFacts",
    "HostPreflightCheck",
    "HostPreflightCheckState",
    "HostPreflightResult",
    "InstallerIssue",
    "InstallerIssueCode",
    "InstallerMutation",
    "InstallerMutationKind",
    "InstallerStepId",
    "InstallerStepPlan",
    "InstallerStepResult",
    "InstallerStepState",
    "ManagedDirectory",
    "ReleaseCandidateInstallMode",
    "ReleaseCandidateInstallPlan",
    "ReleaseCandidateInstallRequest",
    "ReleaseCandidateInstallResult",
    "ReleaseCandidateInstallationRecord",
    "ReleaseCandidateTaskwarriorInputs",
    "ReleaseCandidateTaskwarriorPlan",
    "ReleaseCandidateTaskwarriorResult",
    "SystemProvisioningPlan",
    "SystemProvisioningResult",
    "collect_host_facts",
    "create_base_configuration_plan",
    "create_installation_record",
    "create_system_provisioning_plan",
    "create_taskwarrior_installation_plan",
    "evaluate_host_preflight",
    "install_base_configuration",
    "install_release_candidate_taskwarrior",
    "provision_system_layout",
    "render_installation_record",
    "run_host_preflight",
]
