"""Public action-contract interfaces."""

from lea.actions.confirmation import (
    CONFIRMATION_MATRIX,
    DECISION_TARGET_STATUSES,
    ConfirmationDecision,
    ConfirmationDecisionApplicationResult,
    ConfirmationEvaluation,
    ConfirmationEvaluationResult,
    ConfirmationIssue,
    ConfirmationPolicyApplicationResult,
    ConfirmationRecord,
    ConfirmationRecordResult,
    ConfirmationRequirement,
    apply_confirmation_decision,
    apply_confirmation_policy,
    evaluate_confirmation,
    record_confirmation,
)
from lea.actions.enums import (
    ActionStatus,
    ConfirmationPolicy,
    RiskLevel,
)
from lea.actions.errors import ActionContractError
from lea.actions.execution import (
    ActionExecutionIssue,
    ActionExecutionResult,
    ActionHandler,
    ActionHandlerRegistry,
    execute_action,
)
from lea.actions.models import (
    ActionProposal,
    ExecutionError,
    ExecutionResult,
    generate_proposal_id,
)
from lea.actions.serialisation import (
    action_transition_to_dict,
    confirmation_decision_application_result_to_dict,
    confirmation_evaluation_result_to_dict,
    confirmation_evaluation_to_dict,
    confirmation_issue_to_dict,
    confirmation_policy_application_result_to_dict,
    confirmation_record_result_to_dict,
    confirmation_record_to_dict,
    execution_error_to_dict,
    execution_result_to_dict,
    proposal_from_dict,
    proposal_to_dict,
    transition_issue_to_dict,
    transition_result_to_dict,
    validation_issue_to_dict,
    validation_result_to_dict,
)
from lea.actions.transitions import (
    TERMINAL_STATUSES,
    TRANSITION_TABLE,
    ActionTransition,
    TransitionIssue,
    TransitionResult,
    can_transition,
    transition_proposal,
)
from lea.actions.validation import (
    ValidationIssue,
    ValidationResult,
    validate_proposal_data,
)

__all__ = [
    "CONFIRMATION_MATRIX",
    "DECISION_TARGET_STATUSES",
    "TERMINAL_STATUSES",
    "TRANSITION_TABLE",
    "ActionContractError",
    "ActionExecutionIssue",
    "ActionExecutionResult",
    "ActionHandler",
    "ActionHandlerRegistry",
    "ActionProposal",
    "ActionStatus",
    "ActionTransition",
    "ConfirmationDecision",
    "ConfirmationDecisionApplicationResult",
    "ConfirmationEvaluation",
    "ConfirmationEvaluationResult",
    "ConfirmationIssue",
    "ConfirmationPolicy",
    "ConfirmationPolicyApplicationResult",
    "ConfirmationRecord",
    "ConfirmationRecordResult",
    "ConfirmationRequirement",
    "ExecutionError",
    "ExecutionResult",
    "RiskLevel",
    "TransitionIssue",
    "TransitionResult",
    "ValidationIssue",
    "ValidationResult",
    "action_transition_to_dict",
    "apply_confirmation_decision",
    "apply_confirmation_policy",
    "can_transition",
    "confirmation_decision_application_result_to_dict",
    "confirmation_evaluation_result_to_dict",
    "confirmation_evaluation_to_dict",
    "confirmation_issue_to_dict",
    "confirmation_policy_application_result_to_dict",
    "confirmation_record_result_to_dict",
    "confirmation_record_to_dict",
    "evaluate_confirmation",
    "execute_action",
    "execution_error_to_dict",
    "execution_result_to_dict",
    "generate_proposal_id",
    "proposal_from_dict",
    "proposal_to_dict",
    "record_confirmation",
    "transition_issue_to_dict",
    "transition_proposal",
    "transition_result_to_dict",
    "validate_proposal_data",
    "validation_issue_to_dict",
    "validation_result_to_dict",
]
