"""Public provider-neutral calendar interfaces."""

from lea.calendars.action_handlers import (
    CalendarActionHandlerError,
    calendar_action_handler_registry,
    cancel_calendar_event_action_handler,
    create_calendar_event_action_handler,
    discover_calendars_action_handler,
    list_calendar_events_action_handler,
    list_calendars_action_handler,
    modify_calendar_event_action_handler,
    show_calendar_event_action_handler,
    synchronize_calendars_action_handler,
)
from lea.calendars.android_acceptance import (
    AndroidCalendarAcceptanceIssue,
    AndroidCalendarAcceptanceRecord,
    AndroidCalendarAcceptanceResult,
    create_android_calendar_acceptance_record,
    write_android_calendar_acceptance_record,
)
from lea.calendars.attendees import CalendarAttendee, canonical_attendees
from lea.calendars.collaboration_acceptance import (
    CalendarCollaborationAcceptanceRecord,
    create_calendar_collaboration_acceptance_record,
    write_calendar_collaboration_acceptance_record,
)
from lea.calendars.contracts import (
    CalendarCancelRequest,
    CalendarCollection,
    CalendarCreateRequest,
    CalendarEvent,
    CalendarEventQuery,
    CalendarEventTarget,
    CalendarEventTiming,
    CalendarListCalendarsResult,
    CalendarListEventsResult,
    CalendarModifyRequest,
    CalendarMutationResult,
    CalendarProviderInspectionResult,
    CalendarProviderIssue,
    CalendarShowEventResult,
)
from lea.calendars.expansion import CalendarEventOccurrence, expand_calendar_event
from lea.calendars.proposal_builders import (
    build_calendar_cancel_event_proposal,
    build_calendar_create_event_proposal,
    build_calendar_discover_proposal,
    build_calendar_list_calendars_proposal,
    build_calendar_list_events_proposal,
    build_calendar_modify_event_proposal,
    build_calendar_show_event_proposal,
    build_calendar_sync_proposal,
)
from lea.calendars.provider import CalendarProvider
from lea.calendars.recurrence import CalendarRecurrence
from lea.calendars.synchronization import (
    CalendarSynchronizationInspectionResult,
    CalendarSynchronizationResult,
    CalendarSynchronizer,
)

__all__ = [
    "AndroidCalendarAcceptanceIssue",
    "AndroidCalendarAcceptanceRecord",
    "AndroidCalendarAcceptanceResult",
    "CalendarActionHandlerError",
    "CalendarAttendee",
    "CalendarCancelRequest",
    "CalendarCollaborationAcceptanceRecord",
    "CalendarCollection",
    "CalendarCreateRequest",
    "CalendarEvent",
    "CalendarEventOccurrence",
    "CalendarEventQuery",
    "CalendarEventTarget",
    "CalendarEventTiming",
    "CalendarListCalendarsResult",
    "CalendarListEventsResult",
    "CalendarModifyRequest",
    "CalendarMutationResult",
    "CalendarProvider",
    "CalendarProviderInspectionResult",
    "CalendarProviderIssue",
    "CalendarRecurrence",
    "CalendarShowEventResult",
    "CalendarSynchronizationInspectionResult",
    "CalendarSynchronizationResult",
    "CalendarSynchronizer",
    "build_calendar_cancel_event_proposal",
    "build_calendar_create_event_proposal",
    "build_calendar_discover_proposal",
    "build_calendar_list_calendars_proposal",
    "build_calendar_list_events_proposal",
    "build_calendar_modify_event_proposal",
    "build_calendar_show_event_proposal",
    "build_calendar_sync_proposal",
    "calendar_action_handler_registry",
    "cancel_calendar_event_action_handler",
    "canonical_attendees",
    "create_android_calendar_acceptance_record",
    "create_calendar_collaboration_acceptance_record",
    "create_calendar_event_action_handler",
    "discover_calendars_action_handler",
    "expand_calendar_event",
    "list_calendar_events_action_handler",
    "list_calendars_action_handler",
    "modify_calendar_event_action_handler",
    "show_calendar_event_action_handler",
    "synchronize_calendars_action_handler",
    "write_android_calendar_acceptance_record",
    "write_calendar_collaboration_acceptance_record",
]
